"""
F1 instance tests — using DECLARED synthetic data.

Original real telemetry (Abu Dhabi 2021, FastF1) was removed from this
repository because F1/FOM terms of service restrict redistribution of
timing and telemetry data. Tests now use a 200-sample synthetic lap
generated by instances/f1/data/generate_synthetic.py, which reproduces
the 5 governance scenarios without any real race data.

DATA_LABEL: DECLARED throughout.

What these tests verify:
  - Governance produces valid output on the synthetic lap
  - Each of the 5 scenario phases behaves correctly
  - Touch fires during wheel-to-wheel combat (gap < threshold)
  - Load + attention are complementary and in [0, 1]
  - run.py exits cleanly and produces output matching these invariants
"""

import os
import sys
import subprocess
import hashlib

import numpy as np
import pandas as pd
import pytest

FACTORY = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, FACTORY)

from instances.f1.data_loader import load
from instances.f1.load_model import compute_load
from instances.f1.reflex_trigger import reflex_series
from instances.f1.config import GOVERNED_DRIVER, CHANNELS
from core.governance import govern_series


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def lap():
    return load(GOVERNED_DRIVER)


@pytest.fixture(scope="module")
def pipeline(lap):
    load_arr, attention, decel, gap, corner_load = compute_load(lap)
    reflex_flags = reflex_series(decel, gap)
    active_sets = govern_series(CHANNELS, attention, reflex_flags)
    return lap, load_arr, attention, reflex_flags, active_sets


# ---------------------------------------------------------------------------
# Data integrity
# ---------------------------------------------------------------------------

def test_synthetic_data_loads(lap):
    """Synthetic CSV loads and has all required columns."""
    required = {"Speed", "Throttle", "Brake", "Distance",
                "DistanceToDriverAhead", "X", "Y", "t"}
    assert required.issubset(set(lap.columns)), \
        f"Missing columns: {required - set(lap.columns)}"
    assert len(lap) == 200


def test_synthetic_data_is_declared():
    """Source column must be 'declared' — never 'car' or 'interpolation'."""
    df = load()
    assert df["Source"].isin(["declared"]).all(), \
        "Synthetic data must have Source='declared', not real telemetry markers"


# ---------------------------------------------------------------------------
# Load model invariants
# ---------------------------------------------------------------------------

def test_load_and_attention_are_complementary(pipeline):
    _, load_arr, attention, *_ = pipeline
    assert np.allclose(load_arr + attention, 1.0, atol=1e-9)


def test_load_and_attention_in_unit_interval(pipeline):
    _, load_arr, attention, *_ = pipeline
    assert (load_arr >= 0).all() and (load_arr <= 1).all()
    assert (attention >= 0).all() and (attention <= 1).all()


def test_corner_phase_has_higher_load_than_straight(pipeline):
    """Lateral G in the corner phase should produce higher load than the straight."""
    lap, load_arr, *_ = pipeline
    straight_load = load_arr[:50].mean()
    corner_load   = load_arr[50:100].mean()
    assert corner_load > straight_load, (
        f"Corner load ({corner_load:.3f}) should exceed straight load ({straight_load:.3f})"
    )


def test_braking_phase_produces_high_load(pipeline):
    """Heavy braking (samples 100-124) should produce load > 0.5."""
    _, load_arr, *_ = pipeline
    braking_load = load_arr[100:125].mean()
    assert braking_load > 0.5, \
        f"Braking zone mean load {braking_load:.3f} should exceed 0.5"


# ---------------------------------------------------------------------------
# Reflex (Touch) fires during combat
# ---------------------------------------------------------------------------

def test_reflex_fires_during_combat_phase(pipeline):
    """Touch must fire when gap < combat threshold (samples 125-149)."""
    lap, load_arr, attention, reflex_flags, active_sets = pipeline
    combat_reflex = any(reflex_flags[125:150])
    assert combat_reflex, \
        "Touch (reflex) must fire at least once during the wheel-to-wheel combat phase"


def test_touch_in_active_sets_when_reflex(pipeline):
    *_, reflex_flags, active_sets = pipeline
    for i, (reflex, channels) in enumerate(zip(reflex_flags, active_sets)):
        if reflex:
            assert "Touch" in channels, \
                f"Sample {i}: reflex_flag=True but Touch not in active_sets"


# ---------------------------------------------------------------------------
# Governance output structure
# ---------------------------------------------------------------------------

def test_active_sets_length_matches_data(pipeline):
    lap, *_, active_sets = pipeline
    assert len(active_sets) == len(lap)


def test_recovery_phase_opens_more_channels(pipeline):
    """Straight2 (low load) should admit more channels than the corner (high load)."""
    *_, active_sets = pipeline
    straight2_counts = [len(s) for s in active_sets[150:200]]
    corner_counts    = [len(s) for s in active_sets[50:100]]
    assert np.mean(straight2_counts) >= np.mean(corner_counts), (
        "Recovery phase should open as many or more channels than the corner phase"
    )


# ---------------------------------------------------------------------------
# run.py integration — single test, isolated output path via --output
# ---------------------------------------------------------------------------

def test_f1_run_integration(tmp_path):
    """
    Single subprocess call covers: exit code, required console labels, CSV content.
    Uses --output <tmp_path> so each test run writes to its own isolated file
    and never collides with another test or leaves state in the source tree.
    """
    out_csv = str(tmp_path / "ver_governed.csv")
    result = subprocess.run(
        [sys.executable, os.path.join(FACTORY, "instances", "f1", "run.py"),
         "--output", out_csv],
        cwd=FACTORY, capture_output=True, text=True,
    )
    # exit code
    assert result.returncode == 0, f"run.py failed:\n{result.stderr}"
    # console labels
    assert "THE CORNER" in result.stdout
    assert "THE STRAIGHT" in result.stdout
    # CSV content
    assert os.path.exists(out_csv), "run.py did not create the output CSV"
    df = pd.read_csv(out_csv)
    for col in ["load", "attention", "Touch", "Sound", "Vision", "Presence", "Voice"]:
        assert col in df.columns, f"Missing column {col} in output CSV"
    assert (df["load"] + df["attention"]).between(0.999, 1.001).all()
