"""
F1 instance — data loading.

DATA_LABEL: DECLARED — synthetic lap generated by data/generate_synthetic.py.
The original real telemetry (Abu Dhabi 2021, FastF1) was removed from the
repository because the F1/FOM terms of service restrict redistribution of
timing and telemetry data. The synthetic data reproduces the 5 governance
scenarios that the tests exercise (straight, corner, braking, combat, recovery)
without using any real race data.

To reproduce from scratch: python3 instances/f1/data/generate_synthetic.py
"""

import os
import pandas as pd

DATA_DIR = os.path.join(os.path.dirname(__file__), "data")

# Single synthetic file — driver code argument is accepted for API compatibility
# but ignored (the synthetic lap represents one generic driver).
_SYNTHETIC = os.path.join(DATA_DIR, "synthetic_lap.csv")


def load(code="VER"):
    df = pd.read_csv(_SYNTHETIC)
    df["t"] = pd.to_timedelta(df["Time"]).dt.total_seconds()
    df["Brake"] = df["Brake"].astype(str).str.lower().eq("true")
    for c in ["Speed", "Throttle", "RPM", "nGear", "Distance",
              "DistanceToDriverAhead", "X", "Y"]:
        df[c] = pd.to_numeric(df[c], errors="coerce")
    return df
